services:
  db:
    image: postgres:15
    container_name: weather-db
    restart: always
    environment:
      POSTGRES_DB: weather
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: weather-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
       - ./backend/src:/app/src
       - ./backend/logs:/app/logs

    command: sh -c "npx prisma migrate deploy && npm run start:dev"

  redis:
    image: redis:alpine
    container_name: weather-redis
    ports:
      - "6379:6379"
    restart: always

  frontend:
    image: nginx:alpine
    container_name: weather-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    restart: always


volumes:
  pgdata:
