version: '3.8'

services:
  db:
    image: postgres:15
    container_name: weather-db-test
    restart: always
    environment:
      POSTGRES_DB: weather_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # зміщено для унікальності
    volumes:
      - pgdata_test:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: weather-api-test
    restart: always
    ports:
      - "4000:3000"
    environment:
      NODE_ENV: test
      PORT: 3000
      BASE_API_URL: http://localhost:4000
      DATABASE_URL: postgres://postgres:postgres@db:5432/weather_test
      RESEND_API_URL: https://mock.resend.local
      RESEND_API_KEY: stub-key
      WEATHER_API_URL: https://mock.weather.api
      WEATHER_API_KEY: stub-key
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

  frontend:
    image: nginx:alpine
    container_name: weather-frontend-test
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:80"
    restart: always

volumes:
  pgdata_test:
