services:
  db:
    image: postgres:15
    container_name: weather-test-db
    restart: always
    environment:
      POSTGRES_DB: weather_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgtestdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: weather-test-redis
    ports:
      - "6380:6379"
    restart: always

  test-runner:
    build:
      context: .
    container_name: weather-api-test
    depends_on:
      - db
    env_file:
      - ../.env.test
    command: sh -c "npx prisma migrate deploy && npm run test:integration"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests

volumes:
  pgtestdata: