name: Architecture Validation
on:
  pull_request:
    branches:
      - main

jobs:
  architecture-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: cd backend && npm ci

      - name: Validate architecture
        run: cd backend && npm run arch:validate