name: E2E Tests

on:
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run E2E tests via Docker Compose
        run: docker compose -f docker-compose.test.yaml up --build --abort-on-container-exit e2e-runner

      - name: Clean up
        if: always()
        run: docker compose -f docker-compose.test.yaml down -v
