name: E2E Tests

on:
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install wait-port
        run: npm install -g wait-port

      - name: Prebuild all images
        run: docker compose -f docker-compose.test.yaml build

      - name: Wait for backend health
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:3000/health > /dev/null; then
              echo "✅ Backend is ready"
              break
            fi
            echo "⏳ Waiting for backend... ($i/30)"
            sleep 2
          done

      - name: Run E2E tests
        run: docker compose -f docker-compose.test.yaml up --abort-on-container-exit e2e-runner

      - name: Clean up
        if: always()
        run: docker compose -f docker-compose.test.yaml down -v
